browserName=chrome
chromeVersion=145

#Windows, Mac, Android
osName=Windows

appType=WEBVIEW

androidDeviceName=Android Emulation
androidVersion=16.0

androidBrowser=Chrome

androidAppiumServerIP=127.0.0.1
appiumPort=4723

baseUrl=https://management.yoedu.vn/
apiUrl=https://apigateway.yoot.vn/

client_id=microservices.investment.orders.api
client_secret=2wvJP~ME7UKJ9C;A9eouF);b

timeSleep=3000
objectTimeout=60

